artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://raw.githubusercontent.com/baskar142/datasets/refs/heads/main/luxottica_eyewear_Master.csv
  local_data_file: artifacts/data_ingestion/data.csv
  # No need for unzip_dir since it's a CSV
